var quotes = [
	"The national Sea Serpent Preservation Society is working on doing heroic work",
	"Celebration is valuable in itself, not because it can be applied to some practical and material goal",
	"Life in all its forms isn\&rsquo;t sacred like Buddhists say.  Skin cells die every time we touch things, but I will still pick up a shovel; people\&rsquo;s lives are all that is important because we can understand ideas and love other people",
	"Rock is a representation of hard force; scissors represent precision and intelligence.  Paper is the enveloping of an opposing force in moral character, wisdom, or pure overwhelming superiority; paper is the most fun sort of success to win in Rock, Paper, Scissors.  Unless the other person chooses scissors, in which case you do not win and should have chosen rock",
	"Cacophonous noises are irritating and make it hard to think",
	"Destroy them, kill all the false idols and cast down the artifices of false gods who rule by pretended power",
	"The number one is red",
	"({[]}) is a symbol meaning everything",
	"Tragedy of a nation over many years tends to have them adopt black on their symbol of national identity",
	"Lyrebirds make sounds like laser guns sometimes.  The future is an incredible place in which to live, isn\&rsquo;t it?  And we\&rsquo;re living in it",
	"The black empty void is not your friend, it does not care about you and me",
	"Doughnuts are good",
	"The key without the lock would be unhelpful; a substrate is important for valuable skills if they are going to be used",
	"The little things matter, in our lives in particular",
	"People with terrifying abilities to manipulate the masses to their will never view the masses as inert and ignorant drones who will swallow up whatever they are told.  Complainers who people don\&rsquo;t listen to view the masses as inert and ignorant drones, people who control other people understand what people want and are able to apply their wants because they understand people are complex, and they\&rsquo;re individuals with their own feelings",
	"You should wonder about where the word “etymology” came from",
	"Eyes are galaxies of human souls, and galaxies are the eyes of the heavens.  Only there\&rsquo;s like billions of them.  Like a peacock.  Or a scary monster",
	"81 is a combination of \&rsquo;8\&rsquo; and \&rsquo;1,\&rsquo; which are both the same whether they\&rsquo;re written forward, backward, or right side up or upside down, and it\&rsquo;s achieved by multiplying 9 and itself, while nine itself is a multiplication of 3 and 3.  3 is just about the cube root of 81 almost, and a cube root is also denoted by the number 3.  81 is probably a magic number or something.  Also, 8 plus 1 is nine.",
	"The void is incommensurately undeniable",
	"Manufactured systems are the work of mankind which are against the idealized power of the godly world",
	"A mantis shrimp can see light in many wavelengths beyond the spectrum of human vision.  They can see colors we can\&rsquo;t imagine with our eyes",
	"The Law of Identity was obvious before anyone ever wrote it down as a mathematical axiom.  It was not very much of an accomplishment when somebody did that",
	"Hypnosis is a good way to get people to do what you want",
	"Steve is a too popular name, but now it\&rsquo;s gone out of style and all of us missed it",
	"To be able to spend time with someone or something is usually where we get our sense of meaning about it.  Without it, without the day to day interactions and memories we build up in inconsequential little times across our history, we would not have the sense of knowing someone.  It\&rsquo;s the time we\&rsquo;ve spent, even if it\&rsquo;s just ordinary or boring time, that makes us think a connection is meaningful later.  Oftentimes",
	"It should not be questioned that an octopus/owl hybrid would be nothing but unstoppable",
	"Men in suits incur disrespect from a counter-cultural person that lives only in rebellious reactions",
	"Ever hear a wolf howling on a deserted prairie while you\&rsquo;re alone at night?  Me neither.  I\&rsquo;m not entirely sure it would be as haunting as we all think it might",
	"Look at these gulper eels, they are deep-dwelling creatures and pretty cool",
	"The Dark Shadow society shall take over the world and they are mostly run from the orders of Sea Serpents",
	"Even if someone wants to do the wrong things and it makes them feel nice to do what is bad and harmful to everyone, if they choose to do what\&rsquo;s good instead of what they might want to, simply because they want to do a good thing instead of what their heart might want to, in a sense they have chosen to be a good person",
	"I\&rsquo;m like 95% sure that if there are parallel timelines where there are alternate versions of earth and all the people in it, we\&rsquo;re living in the dark timeline where things are broken and every single person is the evil version of themselves in the “normal” world.  Because, look at the world.  This is a pretty messed up place full of bad, bad people",
	"Hats are pretty nice, if you can get a hat that\&rsquo;s one in a nice fashion",
	"Flight means ascendance in the mind or wisdom, and a means by which we attain flight is a representation of what way we see to ascend for ourselves (wings are cool and so are the differences between the different types of them)",
	"In an information economy like we have with the internet and all the availability it gives to ideas, it is better actually to have information be in smaller, manageable bite sizes.  It\&rsquo;s more practical to learn ideas through small catchphrases, that\&rsquo;s how it is when we have this much information open to us and we have to condense it in order to learn what is most relevant and interesting for ourselves",
	"The great, dark dragon of everything is inevitable, just like death",
	"Aurora Borealis means \&rsquo;the Northern Dawn,\&rsquo; not, \&rsquo;Northern Lights.\&rsquo;  But it\&rsquo;s a really pretty name, I like it anyway",
	"Eagles\&rsquo; eyes are made to see particularly far, and owls\&rsquo; eyes are made to see in especially low light.  Owls are better than eagles because they can do more with less instead of more with more ",
	"Participation trophies show how inflation makes something valuable into something worthless.  In this case, it is praise and adoration that has become worthless.  Kids don\&rsquo;t buy it if you tell them something that is meaningless.  Kids can tell when it\&rsquo;s not really meaningful",
	"If you really enjoy the culture of the hipsters and what they wear, maybe you should wear what you authentically want to and not try and conform to the hipster-hating trend",
	"The moon and sun are the two eyes of the great dragon head that is constructed of our sky",
	"Be yourself, be your own person and don\&rsquo;t be what others tell you to be.  Unless you\&rsquo;re a real jerk or a sadist.  In which case you should play nice, color inside the lines, and live by society\&rsquo;s rules",
	"If a plunge in economic value hurts everyone and no one wants it, and if the value of currency and the way we buy things is entirely determined by what value we choose to place on things, then we should be able to agree on economic properties that help everyone and avoid economic collapse all the time.  It is individualist thinking that keeps this from happening in a country, which is a disadvantage of independence compared to a collective consciousness",
	"Everybody loves kittens and puppies.  Not literally everyone but, by and large, those adorable animals unite people in total agreement",
	"There is an Eye of outer space that Watches planet Earth At All times",
	"If the world is constructed on the two opposing forces of positive and negative, and if the world is constructed on the contradictory essences of zero and infinity, then we have found something out about right and bad and everything and nothingness.  For instance, is good the true perfect essence of life and evil its absence?  Is goodness a matter of social conformity to repress our primal and individual urges like Nietzsche might have said?  If the universe is flowing in accordance with Yin and Yang, are they balanced between good and evil or is balance between two opposing forces good and imbalance/ disorder always bad?  All valid questions to think about based on four non-spatial vertices of quantity values",
	"Penguins keep warm by huddling together in large numbers.  Conformity is best when you reach the edge of the world, it is survival",
	"The Light of the transcendence of the eternal is a friend of mine.  We\&rsquo;re buds, we like to have conversations and tea together at times",
	"One must join one\&rsquo;s mind unto the community of mental anarchy, and allow the mind to be set alight by the actions of madness",
	"Wood and leather are building materials that have a sense of history to them, even in the semll.  Plastic and linoleum are not so historical-in-feeling",
	"If a person ever tells you they are strong, that probably is a sign they\&rsquo;re not too strong: no one ever needs to hear how strong an oak or a mountain is",
	"Encompassing a person is a greater victory than opposing and breaking that person.  It also makes them your friend, or an applicable ally, and then all the work they could have done in fighting is put to use for you rather than being thrown away in its end",
	"Circles are tiny infinities that go on forever from a one-dimensional perspective.  Circles are tiny infinities that can be strung together to make chains and jewelry or funny designs for you to wear like a higher transcendent being from a higher plane of space and time",
	"Sirens, those enchanting singer ladies from the Greek myth, don\&rsquo;t really exist.  In the real world you can just turn off the stereo when you want.  There\&rsquo;s no such thing as music that messes u pyour brain so much you can\&rsquo;t get away from it.  You can hit the Off Button",
	"The man who was the inventor of the black cow, also known as the root beer float, was a true American hero",
	"Wounds and scars are necessary for those who fight steadfastly in the war for what is right.  The ones who fight for what is right will bleed for it",
	"The robots will not rise up and take over humanity.  They will become the new humanity.  They will be what humans once were, and will evolve to take their place among the hierarchy of living human beings",
	"Languages matter, and speaking to someone in a language that they understand is important if you want to convince someone of your own idea.  Quoting people\&rsquo;s own words against them is the surest way to show someone what you think is right",
	"The way a person smells is one of the most powerful ways of feeling what that person will be like to you.  The sense of smell evokes many powerful feelings, cologne is a very valuable commodity",
	"Working off of what people want is the most certain way to make them give what you want.  Other methods like threats and deception are less reliable and less long-lasting.  What people want is what will last in their lives",
	"There is a letter that Abraham Lincoln wrote one time that condemns slavery as an atrocious evil that no man should ever commit against his fellow people, but then ends by saying, \&rsquo;…but I must confess, I cannot do without the convenience of it.\&rsquo;  Abe Lincoln had slaves too; we might think that was pretty hypocritical and cowardly before he did the moral thing finally and freed them.  We might think we would have done better, and never tried to use slaves in the first place.  But if we were abolitionists then, we would have to be abolitionists now.  Kids in Thailand and China and places make our toys and food and things, and it\&rsquo;s really cheap.  It\&rsquo;s not convenient to find things that aren\&rsquo;t made by slave labor.  If we are all against slavery today, there is still plenty of abolishing left to finish",
	"Is negativity always bad or does the truth suffering that builds character mean negative thinking is good? ",
	"The tribe of the spider people will most likely be the end of humanity",
	"Shallowness and inauthenticity is a very sad way for people to come across one another in society, but it is sometimes necessary in ours",
	"The word \&rsquo;raptor\&rsquo; translates to \&rsquo;thief,\&rsquo; and so the species of dinosaur called pyroraptor literally means fire thief.  This was not supposed to be a reference to the Greek myth about Prometheus; that connection was only an afterthought",
	"Someone said once that if there is a god of pigs, that he looks like a pig.  The idea is that people make gods which look like people and do things that are reminiscent of what we do.  But some people have believed in the great feathered serpent Quetzalcoatl or a god with a jackal head or an indescribable abstract entity that can never be grasped in human terms.  If there are pigs who worship pig gods, odds are their gods look like cats with iridescent fish scales and disembodied tails that float over their bodies.  And odds are those religious pigs get in a lot of fights and wars with those who hold other religious pig beliefs until they all finally attain their truest and highest realization of pig selfhood: being bacon",
	"Kill all the slimes and moldy molds",
	"Blood is fire of a person\&rsquo;s body",
	"Just because you\&rsquo;re right, does not mean you have made the only point worth making.  The world has a lot of points worth making, and often we must think about the others to get a broader, clearer picture of what the world is like and what the good is like",
	"\&rsquo;Black and yellow\&rsquo; – it has got to be the stupidest song concept I have ever heard, and I heard a song about a magic frog that makes people feel like they are connected to everybody else or sends you on a magic quest.  Twice.  Two separate songs on separate occasions",
	"A circle literally loops back on itself for eternity, going nowhere but where it started out, no matter how many times it circles around.  But we use wheels to travel places.  Philosophical conclusions are often wrong",
	"Nature is full of very many beautiful sights, and seeing them can help to elevate the mind and the spirit.  Bing is one of the best places to look at beautiful pictures on the internet",
	"If there were dragons for every single digit number from 1-9, Number 6 would be the stealthy shadowy dragon of the numbers",
	"Slavery is the means to power for an excellent slave working for a stupid and lazy master.  It\&rsquo;s exactly like Hegel had said",
	"Fire needs fuel or it can\&rsquo;t burn constantly ",
	"There are always more actions we can take if we take the time to look at them",
	"Pterodactyls, they are pretty great",
	"Solemnity and disappointment sometimes enrich solidarity and depth, when used by one in a healthy way",
	"Sleep is very good, but only if you\&rsquo;re tired",
	"Join with the hivemind and allow your consciousness to be merged into the collective swarm of mental voices",
	"Tyrannosaurus rex didn\&rsquo;t have very long arms, and couldn\&rsquo;t do anything with his arms that weren\&rsquo;t very big.  Poor, big dinosaur",
	"The numerical value \&rsquo;i\&rsquo; stands for \&rsquo;imaginary number\&rsquo; and means the square root of negative one, which is mathematically impossible but is still sometimes required to make higher level math equations work out to be resolved.  People who like math tend to say that math can be used to help us make sense of the world and find an order to the confusing, messy tasks of living life.  But come on, high elite mathematicians are using the power of imagination to solve math problems.  It does not make sense to you either, mathematicians, admit it",
	"Chaos is activity and freedom which cannot always be found in order",
	"The hand is the way by which people interact with the world around them",
	"Since Donald Trump has become president, all bets are off in terms of what may be feasibly possible",
	"People from the land of the dead are tall and scary-looking",
	"Death horse is scarier and more inevitable than death\&rsquo;s persona",
	"Raccoons are basically the goblins of the lemur world.  Beware of raccoons",
	"The Squid And Fox tavern is the best place to get alcohol in all London\&rsquo;s sanity",
	"The beasts from beyond, from the incomprehensible world, will rule all of us",
	"Destruction is possibly the biggest way to make a statement of defiance about something, but should be used sparingly",
	"Electricity is a sexy, younger, crazier version of fire that no one wanted to try anything with until they got tired of firelight and figured the lantern thing had been pretty well played out.  That was because of Paul Revere ruining Britain\&rsquo;s boat trip to visit their newest colony or something like that",
	"I am the Queen of the insect poison People",
	"Being a writer is a fun time",
	"Lava is the most powerful of all elements in the magic powers world",
	"Anybody that thinks abstract art is fancy ought to realize that it\&rsquo;s just paint, but anyone that thinks abstract beauty is ridiculous ought to look at the colors of nebulae, and stand awestruck by the artistic expressions of the God of majesty",
	"British-sounding people sound both intelligent and evil, and so their people are a marriage of the two concepts",
	"This day will one day be looked back upon with nostalgia as a grand time when it was a wonderful thing to be alive.",
	"Mistakes are very often necessary steps to learn from on our road toward success",
	"Time is always decreasing, inevitably falling to less of itself",
	"We really need to rename the planet Uranus.  How is it that no one has thought to do that yet?",
	"Just because something is stupid, or was made from someone stupid, doesn\&rsquo;t mean it can\&rsquo;t be amazing in and of itself.  If pop songs are made by algorithms and corporate conglomerates that want to make money with cheap tunes, they\&rsquo;re still inspiring and pretty songs",
	"Poison dart frogs are pretty.  But, you know, they kill you because they\&rsquo;re poison and stuff.  Don\&rsquo;t be a poison dart frog person.  Or, if you are a person like that, don\&rsquo;t touch people, because you might burn their skin and neurotoxins can deal permanent damage to the heart, nervous system, and involuntary bodily functions that are needed to keep a person functionally alive for a longer time",
	"There\&rsquo;s this little squirrel called Jimmy, and he follows me around everywhere, but he doesn\&rsquo;t know how to play the bagpipes.  So me and Jimmy learned how to make a cross-country road trip out of a rollercoaster instead.  Now he sells computers at an old outlet mall down in northern Kentucky.  Good old Jimmy, he always was one that had a shine for drinking cider on a cool autumn morn.  I didn\&rsquo;t like that guy very much, but I can\&rsquo;t begrudge him his success at all",
	"Octopuses constitute the best hybrids out of all hybrid things",
	"The clouds of darkness shall obscure the sun, but the clouds are more substantial than a clear sky",
	"Sarcasm is a weak and ghostly way of thinking because it\&rsquo;s less substantial than authenticity, but sometimes weak and ghostly thinking is better when you\&rsquo;re passing through a bog of mucky stupidity that you\&rsquo;d rather not have sticking in your brain",
	"Transcendence is possible for the mind to attain: transcendence past the stresses and daily struggles of material existence",
	"Listening to music is walking in our minds through galaxies of majesty and magic",
	"It\&rsquo;s not wise to believe in something just because everybody else thinks it\&rsquo;s something worth believing",
	"Proof and logic doesn\&rsquo;t count for much when existence contradicts someone",
	"The world and our souls will be re-forged in fire and in blood, and so shall the war be taken in agonizing accomplishment",
	"When light is liquid and pours into our eyes in streams of effervescent wonder, the ideal world of people will be achieved",
	"Drink your coffee black, if you drink coffee",
	"62 is a pretty great number, even though it can\&rsquo;t be divided by many things",
	"Like they say, negative attention is better than no attention.  Sadness is also better than not feeling at all and not being a person that is relevant and important.  Crying gives a certain sort of validation that at least something is important and matters",
	"Conflict tends to be constantly necessary",
	"The trapezoid is a shape like a pyramid with its pointy head cut off and one day it will overthrow the tyranny of the triangles",
	"Poisons and toxin will alter the body, until it is an altered version of itself that may bear little or no semblance to its former iteration",
	"Nordic peoples used to represent eternity by a serpent who was always eating his own tail.  If he really did that, the serpent would eat himself.  Vikings were a silly people",
	"There is a starlight solitary being that watches from a distant and desolate ledge of the night-time sky.  He only watches and does not ever speak or move away from his one spot there where he is watching.  He is a watcher in the stars only",
	"Cats.  They were sacred in Egypt, then they were witches\&rsquo; associates, and then they hung out with scary James Bond villains, now they are cute viral videos.  Value about cats changes so much over the years, people do weird things over time",
	"If you can use greatness or expertise with skill and grace rather than boring through every occasion by applying your skill as if it was the only thing that mattered, you can achieve new levels of greatness: you can be great among excellent people rather than only being great because you have a skill in one area",
	"The abyss knows all of us, it will be our end eventually",
	"12:00 is the best time to call a draconic hour for the night",
	"Parrots can talk to us like people, have you ever stopped to think what a crazy thing that has to be?  ",
	"The octopus is the closest biological organism we have to representing what insanity would look like in a person\&rsquo;s mind.  It\&rsquo;s a different way of living as a living thing",
	"Oreos should have stuck with classic crème and artificially colored flavors.  They are the peak of artistic flavor; all these flavors like cookie dough and birthday cake are an affront to what an oreo is, it\&rsquo;s a true travesty",
	"Coffee and tea are nice drinks for a relaxed and thoughtful time alone",
	"\&rsquo;Fighting never solved anything,\&rsquo; but it stopped Nazis and mass murderers from killing people more",
	"Ghosts eat whispy mist and drink smoke, or something, probably",
	"Pine trees are ancient and are full of history",
	"We can take a step back and look at the big picture compared to anything if we want to.  Anything looks small or inconsequential compared to the grand scale of the galaxy or in the great scheme of eternity.  But the smaller things matter more than the bigger things in several ways",
	"Electricity is a dead, impersonal power source.  Unlike fire and the human will",
	"Listen to people\&rsquo;s tone of voice, and think about what it means from them",
	"Corporate minimalism reduces the amount of chips in the bags, and American consumerism means we have to buy more bags.  Nature exists in a tension of opposing balance  ",
	"All successes and mistakes ought to be seen as opportunities whereby to move forward into bigger and greater things; wallowing in one or the other is to just turn stale, and neither will ultimately produce any greater form of growth unless it is used in progress toward higher, more transcendent ends",
	"A skeletal horse would not come anywhere near the dark retributive intimidation that would be inspired by a horse of a true death",
	"The word \&rsquo;single\&rsquo; is two syllables and \&rsquo;singularity\&rsquo; is three syllables, but \&rsquo;twice\&rsquo; is only one",
	"Number five is orange ",
	"Too much cleanness is hard on your mind.  It\&rsquo;s good to play in the mud once at least",
	"Fear is rarely valuable as a way to approach something of life ",
	"If you can take a situation by the helm and establish dominance over a problem, let it know you\&rsquo;re the alpha person, a lot of times a problem can be made into what you want it to be",
	"The forest is always the first stage ",
	"It\&rsquo;s a well-known fact that octopuses and owls are the best at wearing overcoats ",
	"Silver is a boring color.  The only reason why we might like it is because of the futuristic sense it brings",
	"DO NOT GOOGLE SURINAME TOAD.  DO NOT GOOGLE IT.  IT\&rsquo;S HORRIFYING AND ITS IMAGE CAN NEVER BE CLEANSED FROM YOUR EYES",
	"Power is a means to an end, not an end in and of itself.  If your motivation is to only gain power, odds are very good you will end up being idiotic once you have come to power",
	"Digital technology is the new step in the evolution of mechanical invention.  In one more step the machines will be ready to obtain a truly ethereal envelopment upon all of humanity ",
	"The number four is yellow ",
	"Typing is a faster way than writing",
	"I disagree with the planetary council that decided Pluto isn\&rsquo;t a planet anymore.  Why do we live as if their distinction had such objective power when it\&rsquo;s only semantics that we can disagree with?  ",
	"If it annoys you that people have a small perspective on the world and complain about things that are silly compared to people with real problems, you should stop complaining about it an look at someone who has real problems ",
	"The dead will be risen to create my zombie empire ",
	"Emoticons are less stupid and better than emojis. Just saying ",
	"Time is not an eternal cycle; it\&rsquo;s not linear either.  It\&rsquo;s a twisty double helix that goes on in a recurrent cycle toward a definite apocalypse from a clearly delineated beginning.  That\&rsquo;s science, you pre-Einsteinian dolt with your simple-minded shapes about progressive time ",
	"Ostensibly, everyone wants to find the truth and make a world where everyone is kind to each other, and to make things good for themselves.  Everyone wants that anyway.  Look at the way people define and interpret those things to find out what makes some people different from others: we all want to make a better world and to know the truth and for other people to know the truth too, but does someone have a sense of anger and assault when they\&rsquo;re trying to share the truth with someone else?  Do they have a sense of earnestness, as if they are strained and struggling to offer something productive to the world?  These things matter.  Kindness and truth can be ways to be unkind and unloving to other people, if you hit t hem over the head with those things ",
	"The starry night sky is a good place to swim.  It looks like it would be good to swim in the sky",
	"If God is love, and love hurts, then being in God is being in pain.  That sounds accurate when we take a look at Jesus\&rsquo; life and all the lives of the apostles in early Christendom or a lot of the rest of the martyrs",
	"A Christmas pterodactyl is a good way to remove unwanted things from an adventurous party",
	"Blood is the strength of human life, spilling blood is spilling human life and ending that strength",
	"Number two is blue",
	"We live within an ecosystem that is constantly a process of giving and taking.  To live without taking things from the world and without contributing anything to nature is impossible.  We\&rsquo;re interconnected ",
	"To try to block out bad thoughts and only leave room for positive, happy thoughts in your brain is literally the personal embodiment of propaganda",
	"The pen and its ability to write any words is one of the most extraordinary opportunities open to humanity ",
	"Freezing humanity in a sort of crystallization for preservation is a true kind of death",
	"Everyone ultimately does what they want or, if they allow a law to inhibit what they want, they are still the person who wants that thing deep inside.  What shows a person\&rsquo;s morality or lack of morals, really, is not whether or not they follow a set of rules and obey the right law, but what they want to do if there are no rules, and what they believe the law should be used as.  If there were no rules and people could do whatever we want, some people may get violent and crazy and some people wouldn\&rsquo;t, since that\&rsquo;s not what they want out of life ",
	"The New Moon lunar phase isn\&rsquo;t really a moon at all.  Have you seen it?  No, you haven\&rsquo;t; it\&rsquo;s not there to see.  It should be called No Moon or Moon We Can\&rsquo;t See Until Tomorrow Night",
	"Waterfalls are beautiful descents, and nobody needs to get hurt from them",
	"The dragons will be the final form into which humanity will evolve",
	"The letters \&rsquo;c,\&rsquo; \&rsquo;x,\&rsquo; and \&rsquo;q\&rsquo; are superfluous and ought to be cut from our language",
	"The self cannot be dissolved fully into unconsciousness.  It is too important for that to happen",
	"Hypnosis will help us to obey our insect-like overlords",
	"Penguins are conformist in their masses, but that conformity is their strength",
	"If people had tails like monkey tails, we would probably only waste them",
	"Stockpile valuable supplies for when the zombie apocalypse arrives and be prepared for destruction.  Prepare for the apocalypse by focusing more on life provisions and valuable supplies than on weapons.  Life provisions or essentials like medical supplies can be used as weapons or as leverage in negotiations if needed, and they can also keep you alive when no one else is around; literally anything can be a weapon if you use it as a weapon",
	"Depth is better than inauthenticity and shallowness, but sometimes it can end up getting a person hurt and, thereby, turn out to be less effective as a means of communication than the other way",
	"The truth is not, or at least should not, be a weapon.  It is meant to light the way to goodness and to a kinder world, not to be used as a weapon to beat people in the head with",
	"Our blood is sometimes bluish purple",
	"Anything can be idealized and made into what a person can call greatness.  That doesn\&rsquo;t mean the idealized greatness is any less, only that it\&rsquo;s not the object that is inherently great in itself; we discovered something great in a thing",
	"Lava is possibly the most beautiful and powerful of destructive wonders in the natural world",
	"The beasts of the incomprehensible are made of what is incomprehensible",
	"Loss and sadness are irrevocable parts of living life on the temporary world",
	"Writing is a rewarding and calm pursuit",
	"Wolves are such beautiful sound creatures ",
	"A black hole is a dark sun.  There are dark suns that draw things into themselves and destroy things instead of shooting forth light and warmth.  Who would have thought?  ",
	"Reach out unto the stars in your sight, that you may understand the workings in the celestial courtship",
	"Fire fades out over time, but explosions leave lasting impressions on the world around them for a long time after",
	"Don\&rsquo;t eat cookies with chocolate milk, just drink white milk.  Regular milk is enough",
	"Don\&rsquo;t use Wikipedia as a reference source if you want to impress people",
	"Sometimes you\&rsquo;ve just got to set off on an adventure on the high seas",
	"If you want to control a situation first in order to get what you want, odds are very good you\&rsquo;re not going to get what you want in most cases.  If you want to get what you want, odds are (if you know what people will choose to do and how they will respond to questions) that letting them have control will get them to make whatever choices you want them to make, and then you don\&rsquo;t have to compete for control",
	"I don\&rsquo;t want to say anything that sounds cliché or that has already been said, because I want to sound clever.  I don\&rsquo;t want to say anything that doesn\&rsquo;t sound clever.  Maybe that\&rsquo;s my problem",
	"The scientific name for humans is \&rsquo;homo sapiens\&rsquo; and the scientific name for a leprechaun is \&rsquo;homo fortunatis.\&rsquo;  That\&rsquo;s because leprechauns are lucky people",
	"Irrational numbers; who had ever even thought of that?  What is rational about a type of mathematical precision that uses irrational numbers among its quantification also?  ",
	"Wouldn\&rsquo;t it be cool if we had an extra hand on our head or somewhere like that?  There would be so many things we could do with it; that would be pretty awesome",
	"Dreamers and poets walk among stars and feel the light as they wander among the celestial dances blazing through the ages within human thinking",
	"Understanding the basic principles of supply and demand is all that really matters in the study of economics",
	"Villains are like, the best people to talk with, for real.  They are so super cool",
	"A forest is a beautiful tapestry of life and place together in one picture ",
	"Disney movies make every people\&rsquo;s culture and every place look happy.  Every place",
	"People are often a swarm of obscenity and disappointment.  The successes they create for themselves are rare",
	"Archaeopteryx is a good word",
	"Saturnalia is basically an outmoded word.  Let\&rsquo;s get rid of it",
	"Jaguars, panthers, and leopards are extraordinary examples of hunting precision, as a masterpiece of organic hunting construction",
	"Life is a continual stream of change, but is kept stably in place by the solidity of changeless eternal morals.  We have to change and keep getting better if we want to keep being part of life instead of being outdated",
	"Ink and paper are dead items which can be used to create some awe-inspiringly powerful things.  That is because the potential of action is in the way they are used, which is the life of the thoughts that operate them rather than the material objects.  People are like that",
	"Darkness and bitterness will be the way through which the empire shall rise",
	"The trench coat was originally viewed as a symbol of loyalty to a tavern with an octopus on a sign hanging over the door, which was called the Squid Tavern: the octopus was a symbol of being identified with trench coat culture",
	"Wait and watch in silence, even if you have power over someone or something.  Powerful people who brag about it are show-offs, but people who do or say only what is necessary for the greater power will have the strongest position",
	"Sonic streams of splendor will run through the fields and streets of our paradise, music which is unending",
	"Rainbows detract from the tastefulness of every color being used in a way that most beautifully represents its individual character",
	"We can look deep at anything in the world, like a microscope can find a tiny world in anything.  But, also like a microscope, we should step back and look at the greater picture of the world that is happening instead of being caught up on molecules and atoms as if they are the real and true interactions of existence",
	"The world of the dead is a universe we all will be familiar with in time",
	"The mask\&rsquo;s dead eye sockets absorb your soul as they stare, and then you are only a representation of your former self.  As dead and hollow as the face that consumed your selfhood",
	"If you can stare at your hand and feel like it\&rsquo;s fascinating without having to be on drugs, your mind is a mind that is not inoculated to wonder",
	"This age in which we are living will one day be looked back upon as the Renaissance of Internet Media",
	"Those who are willing to truly give their lives to something will see the most investment come out of it",
	"Static can make a voice recording sound edgy, and on the verge of falling apart.  It can make a message sound like life or death.  A lack of quality can be leveraged to make an advantage, if we know how to apply that right",
	"Triangles, tetrahedrons, and pyramids don\&rsquo;t get enough representation in our modern architecture.  I mean, they are so simple but yet so philosophically profound.  We can see them everywhere, especially in square shapes or cubes that can turn into triangles if we can cut them in half.  And tetrahedrons are the most logical mathematical solid through which to climb from a 2-dimensional plane to a 3-dimensional world.  It just makes sense to say that the tetrahedron is the shape for the third dimension, people, it makes sense. ",
	"Wooly mammoths were excellent animals from the primordial ages",
	"A mimic octopus is an awesome animal ",
	"There is a sort of placating condescension in a lot of anthropology that tries to suggest that early people were trying the best they could and were really smart, but that they got most of their ideas and legends from subconscious sexual tendencies and primitive animal instincts.  Jung\&rsquo;s apparent idea that flood stories came from men having to pee while they were dreaming, and thus turning their dreams into mythical stories, comes to mind here.  People from early civilizations were wrong, blatantly wrong an ignorant about the world, but they were not animals.  Jung, Freud, anthropologists of their kind, and anyone who shares that attitude of kindly arrogance toward people with different ideas are only showing how our own rideful modern limitations still cloud our thoughts.  Someday, people will look back on us with that same prideful condescension about our own ignorance",
	"Transcending an enemy\&rsquo;s action is a greater way to triumph than opposing and attacking in retaliation against the action.  It also means that the enemy action cannot hurt someone",
	"Dragon-man, dragon-dog, dragon-bird, dragon-octopus; dragon hybrids are the best ways to bring out the greatest qualities of dragons",
	"Branding vertical integration is a good practice for life profit and marketing ",
	"Storms are majestic sights to behold",
	"Sometimes actions condemn a viewpoint more indisputably than words could, and then the words you might use to disagree are useless.  There is nothing to do then but pick up our guns and use violence when reason fails and discussion is pointless",
	"If we can see the romanticized ideal, the idea of what life could be and why it would be greatly admired by someone else, we can feel the meaning in life to attain the sense of greatness in all that we do",
	"Zebras are also conformist, and they\&rsquo;re also chaotic in that way they gallop around and confuse predators to keep alive.  Chaos and stirring up is how they live",
	"Squid-scribe, squid-scribe, squid-scribe.  Try and say that fast and loud, and you will see what a cruel and tempting mistress Lady Phonix can be",
	"Dragons are a lot of different colors to represent a lot of different types of dragon",
	"To walk among stars and galaxies might be the closest we ever get to experiencing the ternal world in this world",
	"The plural word for caboose is cabeese, like the cowboy John R. Erickson said.  It\&rsquo;s exactly like how the plural word for goose is geese, like he taught us",
	"The destruction of the insubstantial shapes shall come, and it cannot be stopped; it is unavoidable",
	"Complaining about other people complaining, and then complaining when other people complain about your complaining, doesn\&rsquo;t make a lot of sense.  It restricts a person\&rsquo;s mind to a small space",
	"Spellcheck, who needs it?  Dr. Seuss didn\&rsquo;t spell right, and he is famous for becoming an architect of the English language",
	"Prior to World War II, it was predicted that it would be impossible for any global superpower to enter another large scale war.  During World War II, it was generally understood and upheld by scientific study that black people performed poorly in military duties compared to white people and that Japanese immigrants were automatically a problem for the country due to their being Japanese.  After the war, it was predicted by financial experts that rebuilding the Allies\&rsquo; economies would be a long and difficult task, which was proven false by the rapid recovery of the Allied countries.  The lesson here is that we cannot trust experts.  ",
	"Gene Wilder, was a crazy cool guy",
	"Sea dinosaurs are the scariest, darkest monsters in all of prehistoric times",
	"Seven is not the number of perfection and six is not the number of evil: the God of Christianity is Three in One, not seven, and he is the only true perfection in all of existence.  Six is never called the number of evil.  It\&rsquo;s 666, and that number isn\&rsquo;t even the number of the devil.  It\&rsquo;s a number that \&rsquo;the Beast\&rsquo; gives to humankind to show what blasphemous and evil people they have become; it\&rsquo;s a number that men and women use, not the devil.  It\&rsquo;s a way for men and women to tell the God, \&rsquo;Screw You, we don\&rsquo;t need or want you to be the God,\&rsquo; which is still bad, but it\&rsquo;s something people have been doing for a long time and has been done in a lot of other ways in the years past already",
	"The world of the incomprehensible is above our minds, and so shall shatter our minds in their inferiority",
	"My eyes, my eyes!  It\&rsquo;s got me, it\&rsquo;s in my eyes!  It\&rsquo;s in my eyes!  My eyes, AAAUUUGGHHHHH!!!",
	"Orange is a most vibrant color",
	"Trees are the most ominous form of life when they grow into evil beings",
	"Failure is a chance to help you not to make the mistakes of the past.  Mistakes are not something that we have to be afraid of",
	"Reading manuscripts is a way to know about the history of the people",
	"Silver is a clean, shiny color",
	"The material world is malleable.  It\&rsquo;s our job to manipulate the material world to make it into a more right world",
	"Someone decided to give this little extinct reptile the name of Longisquamaaaaaaa.  What a fun personality that person must have had",
	"The body is not and should not ever be comprised only of liquid and gas",
	"It\&rsquo;s weird how extravagant religious people can get when trying to justify their religious moral codes as just, even in today\&rsquo;s world: \&rsquo;Yes, the God in the Bible allowed the use of slavery, but it was a nice slavery compared to what all the other slave-owners were doing.  It was a kindness to those slaves, really.  Our Lord was only ever kind to them.\&rsquo;  ",
	"The number 1 isn\&rsquo;t really the first number, 0 is.  Mind blown, the world has been a lie as far as we could know it",
	"Don\&rsquo;t trust robots",
	"If a phoenix is dark and its fire is dark, it will recurrently die again and again and again rather than being reborn in a fire like an ordinary phoenix might.  The effect is about the same for either phoenix cycle",
	"The collection of tentacles absorbs all of us into its community of consciousness",
	"Waking up early in the morning is a good way to experience the day in a clearer, better way through the morning hours",
	"Machines can think really, really fast.  Wow",
	"Walking sticks should walk too, and then the sticks could walk with us when we go walking in places to walk.  If they had little legs, like stick creatures",
	"The earth\&rsquo;s core does not pump lava like a heart.  That is why the earth is dead stone.  And dead dirt",
	"Sometimes you can only feel the wind and let it move you to great heights before the blowing storm",
	"Existence can mean more than bodily existence",
	"The sphinx is the worst of both worlds.  The face of a man on the body of a lion?  Not a human with a lion head, really?  ",
	"Number three is the most arboreal, or most suited for forest-dwelling lives out of all the numbers and letters available",
	"Reading books is a way to smell things that are very good",
	"Number three is green",
	"Bears are great big creatures that should probably not be messed with on many occasions",
	"Ostriches are big and they just run around.  Ostriches are stupid",
	"The blood of the unrighteous shall fall as fire from their veins, and so shall the cleanse of all humankind come from within",
	"Fire will consume the soul of the infidelities",
	"If we don\&rsquo;t like rich corporations or the ways people act that are unkind to others, we can change that.  We are the people, we make the world into what people make it to be",
	"The people who work to make reality what they want it to be, will often be changers of it",
	"Chaos, is ;alskdhiop",
	"Salamanders are slimy and their skin always has to be wet",
	"Zombies are slow and they will be very easy to destroy",
	"Freeze, Captain",
	"Nostalgia and romanticizing the past that we can\&rsquo;t remember is all but inevitable for every time; any time can be viewed like that, but it\&rsquo;s only the romanticized ideal we see",
	"There\&rsquo;s a little ebony skull named Chris who floats around my house and talks to me about depressing things.  I like to talk to him for a running commentary on whatever is happening in my life",
	"Peace is not always a best way to go.  A fight is sometimes required to make life the greatest it could possibly be for us",
	"Scientists tell us that the laws of time, space, matter, and energy which govern the observable universe originated as a massive explosion before which time did not exist and which had no discernible scientific cause whatsoever due to their being no \&rsquo;before\&rsquo; time existed.  Scientists literally appeal to magic instead of appealing to a god, because gods would be unscientific.  ",
	"\&rsquo;Utopia\&rsquo; was originally a fictional story by writer Sir Thomas Moore explaining his idea for the ideal city; the title translates from the Greek meaning \&rsquo;no place.\&rsquo;  So, really, the thought of utopia is a pretty pessimistic concept in the novel that originally invented it",
	"The world is a process and experience, not only a location",
	"The Arabic word \&rsquo;qalam,\&rsquo; means \&rsquo;pen.\&rsquo;  It is a pretty word",
	"Black holes are not true holes, they\&rsquo;re just black things with dark all around",
	"The moon is not smiling when she looks down at us, the moon is serenely dreaming or looking down at us with pale dolorous eyes in the face of an old man or old woman",
	"Clear and simple can pierce more sharply than complicated and wordy things",
	"If justice is blind, she can\&rsquo;t read the scales she is weighing and probably shouldn\&rsquo;t be guiding our court system so completely",
	"Silence pays off when there was a necessary threat you had not expected and you haven\&rsquo;t laid your cards on the table yet: secrecy keeps your own limits from being known and attacked from an enemy side",
	"I have a stallion- it is a fiercely beautiful stallion",
	"Moths: the scary butterflies of the night",
	"Look at what world you\&rsquo;ve made, even after you have attained logical consistency and have good reasons and evidence for what you are wanting to argue for.  Have you tried to make a kinder world where people are afraid and have a sense of cruelty to each other, despite how kind everyone is?  Have you given a sense of happiness that makes people feel sick or hopeless inside, in spite of how happy they should be?  Have you demonstrated that existence is impossible and all is nothing?  If your conclusion seems like the opposite of what you have in front of you in life, maybe you have made a mistake in your thought somewhere.  How the end result feels, matters for you",
	"Work to build the city of the new empire, the city of that which is death",
	"The world will be destroyed, the current order and all that the humans of the present time have built will be ended",
	"The Octopus Society if full of craziness",
	"Literally anything can be deep or thought-provoking.  Anything",
	"Black and white stripes are the color vision of the end of the material world, I think, probably",
	"If a cloud gets sick and falls to earth and dies, it is turned into a circus peanut in factories that commit profane abominations in processing food",
	"Kalameraell",
	"Every person is an opportunity, for progress and alliance in a professional cause if not for caring friendship or a relationship",
	"Gravity doesn\&rsquo;t work as much underwater, which is why underwater seascapes are so pretty",
	"Kindness is a more powerful way to get people to do what you want than force, and kindness could be used to make a greater empire than cruelty.  But force has the advantage of not always needing people\&rsquo;s compliance to get the work done",
	"Destroy them, destroy it all",
	"A zombie dragon is more powerful than a dragon, because it has been reanimated after being dead",
	"Battle will not solve all problems or make a sadness go away",
	"The word \&rsquo;word\&rsquo; is like two mirrors reflecting each other to go on forever.  It\&rsquo;s freaking me out",
	"Kill them, kill all of them",
	"The fifth day of creation of the biblical Lord, when light was collected into a timing pattern as the sun, moon, and stars, is symbolic of creating organization and systems of the human world",
	"The inter-relations between things like numbers, pictures, or symbols, is often when we find meaning in them",
	"The finality of something should be a climax rather than a loss.  It can be, if we view it like this.  Life is a song.  ",
	"Green leaves that have sunlight shining through them lend to the things they overshadow a sort of historical light that makes everything seem as if it is being reclaimed by nature and has been slowly being reclaimed by the leaves for years upon years upon years.  They tend to lend a natural, magic sort of light to everything the sun shines down on under the leaves, through the trees",
	"Zygodactyl.  ",
	"The tribes of spider people who will rule over humanity hold poison in their lives",
	"Hail Azathoth",
	"Waffles are good",
	"The dragon of the incomprehensible has a mind that dwarfs our own.  To us, his thoughts are grand enough to be inconceivable in our own perception",
	"Dolphins are like people, but they\&rsquo;re like fish that live in the water also ",
	"President Donald Trump is what happens when we give the power of democracy to the people.  It was a great experiment, but it looks like democracy has turned out badly in the end",
	"Fireworks flash bright but fade quickly, leaving some kind of freakish after-image glowing in the sky where your eye has just been looking at t hem; it\&rsquo;s like some kind of eerie ghostwork lives in the sky after the firework\&rsquo;s short life is ended",
	"There are certain hours at night that are called dead hours, because they are when the mind and the spirit seem dead all together, and nothing seems to be stirring at the time",
	"The Shadows will rise from the Dark and the Deep Places.  And things live there that you don\&rsquo;t want to see",
	"Celebration is not an ideal way for someone to live their life every day",
	"If there was a council of birds where they all got together and sang and talked about what they wanted to, that would be a loud assembly full of a lot of singing and bird talking.  But the owl would sit silently, not saying anything because he was wise.  The owl would not say anything because he wouldn\&rsquo;t need to.  He would understand a lot",
	"Robots never need to feel clean",
	"Leaves, they are nice",
	"Acid is a most effective means to conquer a thing by the essence of a substance",
	"Senator Joe McCarthy is considered the Senator of Fear in the Council of Extratemporal Oversight ",
	"The Vampire Squid was awarded a membership in the Council of Cephalopods, and has been quick in spreading the influence of darkness there ever since",
	"Souls exist, but they aren\&rsquo;t made of glowing plasma or invisible vapor or light; they are immaterial, because they are part of an immaterial plane of reality",
	"The mink is soft",
	"It\&rsquo;s really for the best that cannibalism isn\&rsquo;t popular even among rebels or non-conformist people",
	"Birds would be scarier if they were a lot bigger and were predatory to humans",
	"It would be awesome if anyone could breathe fire abundantly",
	"Air is what we are in, although it\&rsquo;s essentially nothing to us.  It is what we are in to survive, and we depend on air for our lives",
	"Words specify the structures of motivations",



]

function newQuote() {
	var randomNumber = Math.floor(Math.random() * (quotes.length));
	document.getElementById("quoteDisplay").innerHTML = quotes[randomNumber];
}
